# Welcome to Serverless!
#
# This file is the main config file for your service.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: getdocumentsfromcomino
plugins:
  - serverless-dynamodb-local

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: dotnetcore2.1
  region: eu-west-2

package:
  artifact: bin/release/netcoreapp2.1/comino-printing.zip

functions:
  fetchdocumentids:
    handler: Lambda::AwsDotnetCsharp.Handlers::FetchAndQueueDocumentIds
    role: arn:aws:iam::775052747630:role/LBH_Lambda_Execution
    events:
      - schedule: rate(1 minute)
    environment:
      COMINO_DB_CONN_STR: ${ssm:/hn-comino-printing/${self:provider.stage}/COMINO_DB_CONN_STR~true}
      ENV: ${self:provider.stage}

  listenForSqsEvents:
    handler: Lambda::AwsDotnetCsharp.Handlers::ListenForSqsEvents
    role: arn:aws:iam::775052747630:role/LBH_Lambda_Execution
    events:
      - sqs: arn:aws:sqs:eu-west-2:775052747630:sqs-comino-printing-${self:provider.stage}

resources: # CloudFormation template syntax from here on.
  Resources:
    cominoLetters:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "Letters"
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
          - AttributeName: Code
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
          - AttributeName: Code
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    sqsQueueCominoPrintingDocumentIds:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: sqs-comino-printing-${self:provider.stage}

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
